Repository backstagephp/fields, pull requests merged in 2025-09, with the labels that each got.

#26 fix: disable array casting
  src/Fields/RichEditor.php
Labels: bug

#27 fix: rich editor form fill issues
  src/Fields/RichEditor.php
Labels: bug

#28 feat: auto assign workflow
  .github/workflows/pr-auto-assign.yml
Labels: enhancement

#29 feat: remove content cleaning
  resources/css/fields.css
  src/Concerns/HasContentCleaning.php
  src/Fields/RichEditor.php
  src/Services/ContentCleaningService.php
  src/helpers.php
Labels: enhancement

#30 feat: remove live and set json to true
  src/Fields/RichEditor.php
Labels: enhancement

#31 fix: disable indenting and drag n drop
  src/Fields/Repeater.php
Labels: bug, fix

#19 feat: validation and conditional fields
  README.md
  src/Contracts/FieldContract.php
  src/Fields/Base.php
  src/Fields/Checkbox.php
  src/Fields/CheckboxList.php
  src/Fields/Color.php
  src/Fields/DateTime.php
  src/Fields/FormSchemas/BasicSettingsSchema.php
  src/Fields/FormSchemas/ValidationRulesSchema.php
  src/Fields/FormSchemas/VisibilityRulesSchema.php
  src/Fields/Helpers/FieldOptionsHelper.php
  src/Fields/KeyValue.php
  src/Fields/Logic/ConditionalLogicApplier.php
  src/Fields/Logic/VisibilityLogicApplier.php
  src/Fields/MarkdownEditor.php
  src/Fields/Radio.php
  src/Fields/Repeater.php
  src/Fields/RichEditor.php
  src/Fields/Select.php
  src/Fields/Tags.php
  src/Fields/Text.php
  src/Fields/Textarea.php
  src/Fields/Toggle.php
  src/Fields/Validation/ValidationRuleApplier.php
  src/Filament/RelationManagers/FieldsRelationManager.php
  src/Models/Field.php
Labels: enhancement
